namespace Tapeory.Api.Storage;

/// <summary>
/// Resolves a relative storage path against a root directory and rejects anything that would
/// escape it (e.g. via "..", absolute paths, or platform-specific tricks), guarding against path
/// traversal even though relative paths are normally generated by the server itself.
/// </summary>
public static class StoragePathGuard
{
    public static string ResolveWithinRoot(string root, string relativePath)
    {
        if (string.IsNullOrWhiteSpace(relativePath))
        {
            throw new UnauthorizedAccessException("A storage path is required.");
        }

        var fullRoot = Path.GetFullPath(root);
        var candidate = Path.GetFullPath(Path.Combine(fullRoot, relativePath));

        var rootWithSeparator = fullRoot.EndsWith(Path.DirectorySeparatorChar)
            ? fullRoot
            : fullRoot + Path.DirectorySeparatorChar;

        if (!candidate.StartsWith(rootWithSeparator, StringComparison.OrdinalIgnoreCase))
        {
            throw new UnauthorizedAccessException(
                $"Resolved path '{candidate}' escapes the storage root '{fullRoot}'.");
        }

        return candidate;
    }
}
